# -*- coding:utf-8 -*-


SUCCESS = 0

CREATE_USER_ERROR = 4001
CREATE_USER_ACCOUNT_NAME_EXISTS = 4002
CREATE_USER_ACCOUNT_PHONE_BIND_ALREADY = 4003
EMPTY_ACCOUNT_NAME_OR_PHONE = 4004

LOGIN_ERROR = 5001
LOGIN_ERROR_INVALID_USERNAME = 5002
LOGIN_ERROR_EMPTY_USERNAME = 5003
LOGIN_ERROR_WRONG_PASSWORD = 5004
LOGIN_ERROR_EMPTY_PASSWORD = 5005

ERROR_MSG = {
    SUCCESS: u"成功",
    CREATE_USER_ERROR: u"创建用户出错",
    CREATE_USER_ACCOUNT_NAME_EXISTS: u"用户名已注册",
    CREATE_USER_ACCOUNT_PHONE_BIND_ALREADY: u"该手机号已被绑定",
    EMPTY_ACCOUNT_NAME_OR_PHONE: u"用户名密码不能为空"
}


def get_code_detail(code):
    try:
        return ERROR_MSG[code]
    except KeyError:
        print "Unknown Error code"